# Generated by Django 3.1.3 on 2020-11-06 21:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20201106_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50000, null=True),
        ),
    ]
