# Generated by Django 3.1.3 on 2020-11-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20201106_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
