# Generated by Django 3.1.3 on 2020-11-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20201106_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=250),
        ),
    ]
